<?php

function seedTable() {
    $beans =[
        [
            "name" => "INDONESIA Medium",
            "image" => "beans1.jpg",
            "alt" => "Photo by Cup of Couple from Pexels",
            "text" => "Indonesian coffee beans. Tasty coffee espically for cappuccino.",
            "weight" => 1,
            "price" => 25,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 30,
            "id" => 1,
            "quantity" => 0,
            "category" => 'medium',
            "show" => true,
        ],
        [
            "name" => "COLOMBIA Medium",
            "image" => "beans2.jpg",
            "alt" => "Photo by Cup of Couple from Pexels",
            "text" => "colombian coffee beans.",
            "weight" => 1,
            "price" => 28,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 50,
            "id" => 2,
            "quantity" => 0,
            "category" => 'medium',
            "show" => true,
        ],
        [
            "name" => "COLOMBIA Blond",
            "image" => "beans3.jpg",
            "alt" => "Photo by Denys Gromov from Pexels",
            "text" => "Colombian coffee beans.",
            "weight" => 0.5,
            "price" => 13,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 2,
            "id" => 3,
            "quantity" => 0,
            "category" => 'blond',
            "show" => true,
        ],
        [
            "name" => "BRAZIL Dark",
            "image" => "beans4.jpg",
            "alt" => "Photo by Thirdman from Pexels",
            "text" => "Brazilian coffee beans.",
            "weight" => 1,
            "price" => 30,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 34,
            "id" => 4,
            "quantity" => 0,
            "category" => 'dark',
            "show" => true,
        ],
        [
            "name" => "BRAZIL Blond",
            "image" => "beans5.jpg",
            "alt" => "Photo by Los Muertos Crew from Pexels",
            "text" => "Brazilian coffee beans.",
            "weight" => 1,
            "price" => 28,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 9,
            "id" => 5,
            "quantity" => 0,
            "category" => 'blond',
            "show" => true,
        ],
        [
            "name" => "INDIA Dark",
            "image" => "beans6.jpg",
            "alt" => "istock",
            "text" => "Indian coffee beans.",
            "weight" => 1,
            "price" => 30,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 3,
            "id" => 6,
            "quantity" => 0,
            "category" => 'dark',
            "show" => true,
        ],
        [
            "name" => "ETHIOPIA Medium",
            "image" => "beans7.jpg",
            "alt" => "Photo by Ave Calvar Martinez from Pexels",
            "text" => "Ethiopian coffee beans.",
            "weight" => 1,
            "price" => 27,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 9,
            "id" => 7,
            "quantity" => 0,
            "category" => 'medium',
            "show" => true,
        ],
        [
            "name" => "INDIA Medium",
            "image" => "beans8.jpg",
            "alt" => "Photo by bacho nadiradze from Pexels",
            "text" => "Indian coffee beans.",
            "weight" => 0.5,
            "price" => 12,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 2,
            "id" => 8,
            "quantity" => 0,
            "category" => 'medium',
            "show" => true,
        ],
        [
            "name" => "ETHIOPIA Blond",
            "image" => "beans9.jpg",
            "alt" => "Photo by Cup of Couple from Pexels ",
            "text" => "Ethiopian coffee beans.",
            "weight" => 1,
            "price" => 29,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 17,
            "id" => 9,
            "quantity" => 0,
            "category" => 'blond',
            "show" => true,
        ],
        [
            "name" => "INDIA Blond",
            "image" => "beans10.jpg",
            "alt" => "Photo by Alexas Fotos from Pexels ",
            "text" => "Inidan coffee beans.",
            "weight" => 1,
            "price" => 30,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 22,
            "id" => 10,
            "quantity" => 0,
            "category" => 'blond',
            "show" => true,
        ],
        [
            "name" => "INDONESIA Blond",
            "image" => "beans11.jpg",
            "alt" => "Photo by Engin Akyurt from Pexels",
            "text" => "Indonesian coffee beans.",
            "weight" => 1,
            "price" => 27,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 4,
            "id" => 11,
            "quantity" => 0,
            "category" => 'blond',
            "show" => true,
        ],
        [
            "name" => "INDONESIA Dark",
            "image" => "beans12.jpg",
            "alt" => "Photo by Ryutaro Tsukata from Pexels",
            "text" => "Indonesian coffee beans.",
            "weight" => 1,
            "price" => 30,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 44,
            "id" => 12,
            "quantity" => 0,
            "category" => 'dark',
            "show" => true,
        ],
        [
            "name" => "BRAZIL Medium",
            "image" => "beans13.jpg",
            "alt" => "Photo by Cup of Couple from Pexels",
            "text" => "Barazilian coffee beans.",
            "weight" => 0.5,
            "price" => 14,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 83,
            "id" => 13,
            "quantity" => 0,
            "category" => 'medium',
            "show" => true,
        ],
        [
            "name" => "VIETNAM Blond",
            "image" => "beans14.jpg",
            "alt" => "Photo by cottonbro from Pexels",
            "text" => "Veitnamian coffee beans.",
            "weight" => 1,
            "price" => 25,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 60,
            "id" => 14,
            "quantity" => 0,
            "category" => 'blond',
            "show" => true,
        ],
        [
            "name" => "VIETNAM Dark",
            "image" => "beans15.jpg",
            "alt" => "Photo by Nicola Barts from Pexels",
            "text" => "Veitnamian coffee beans.",
            "weight" => 1,
            "price" => 28,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 4,
            "id" => 15,
            "quantity" => 0,
            "category" => 'dark',
            "show" => true,
        ],
        [
            "name" => "VIETNAM Medium",
            "image" => "beans16.jpg",
            "alt" => "Photo by lyncoln Miller from Pexels",
            "text" => "Veitnamian coffee beans.",
            "weight" => 1,
            "price" => 27,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 58,
            "id" => 16,
            "quantity" => 0,
            "category" => 'medium',
            "show" => true,
        ],
        [
            "name" => "PERU Blond",
            "image" => "beans17.jpg",
            "alt" => "Photo by Mariakray from Pexels",
            "text" => "Peruvian coffee beans.",
            "weight" => 1,
            "price" => 28,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 45,
            "id" => 17,
            "quantity" => 0,
            "category" => 'blond',
            "show" => true,
        ],
        [
            "name" => "PERU Dark",
            "image" => "beans18.jpg",
            "alt" => "Photo by Pavel Danilyuk from Pexels",
            "text" => "Peruvian coffee beans.",
            "weight" => 0.5,
            "price" => 16,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 56,
            "id" => 18,
            "quantity" => 0,
            "category" => 'dark',
            "show" => true,
        ],
        [
            "name" => "UGANDA Medium",
            "image" => "beans19.jpg",
            "alt" => "Photo by Cup of Couple from Pexels",
            "text" => "Ugandan coffee beans.",
            "weight" => 1,
            "price" => 26,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 54,
            "id" => 19,
            "quantity" => 0,
            "category" => 'medium',
            "show" => true,
        ],
        [
            "name" => "UGANDA Dark",
            "image" => "beans20.jpg",
            "alt" => "Photo by Lisa from Pexels",
            "text" => "Ugandan coffee beans.",
            "weight" => 1,
            "price" => 28,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 30,
            "id" => 20,
            "quantity" => 0,
            "category" => 'dark',
            "show" => true,
        ],
    
    ];

    $sql = "TRUNCATE `beans`.`webshop`";

    query($sql);

    foreach ($beans as $bean) {
        $bean['created_at'] = date('Y-m-d H:i:s');

        insert($bean, 'webshop');
    }
  
};
