<?php

function seedTable() {
    $cups =[
        [
            "name" => "Black coffee cup set",
            "image" => "blackcoffeec.jpg",
            "alt" => "Photo by Chevanon Photography from Pexels",
            "text" => "A beautifull set of coffee cups. 6 stuks",
            "stucks" => 6,
            "price" => 35,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 120,
            "id" => 1,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "Beautifull brown coffee cup",
            "image" => "nicebrowncoffeec.jpg",
            "alt" => "Photo by Pelageia Zelenina from Pexels",
            "text" => "A beautifull coffee cup.",
            "stucks" => 1,
            "price" => 15,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 2,
            "id" => 2,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "brown coffee cup set",
            "image" => "browncoffeec.jpg",
            "alt" => "Photo by Valeriia Miller from Pexels",
            "text" => "A beautifull set of coffee cups. 2 stuks",
            "stucks" => 6,
            "price" => 15,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 80,
            "id" => 3,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "White coffee cup Set",
            "image" => "whitecoffeec.jpg",
            "alt" => "Photo by Alin Luna from Pexels",
            "text" => "A nice white set of coffee cups. 6 stuks",
            "stucks" => 6,
            "price" => 40,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 10,
            "id" => 4,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "Grey coffee cup Set",
            "image" => "greycoffeec.jpg",
            "alt" => "Photo by Vitaly Vlasov from Pexels",
            "text" => "A large grey set of coffee cups. 6 stuks",
            "stucks" => 6,
            "price" => 58,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 5,
            "id" => 5,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "Nice coffee cup Set",
            "image" => "nicecoffeec.jpg",
            "alt" => "Photo by Marta Dzedyshko from Pexels",
            "text" => "A nice beautifull set of coffee cups. 12 stuks",
            "stucks" => 12,
            "price" => 120,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 15,
            "id" => 6,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "Pottery coffee cup",
            "image" => "potterycoffeec.jpg",
            "alt" => "Photo by Cup of Couple from Pexels",
            "text" => "A pottery beautifull coffee cup.",
            "stucks" => 1,
            "price" => 12,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 20,
            "id" => 7,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Beautifull coffee cup",
            "image" => "beautifullcoffeec.jpg",
            "alt" => "Photo by SpotwizardLee from Pexels",
            "text" => "A beautifull and cozy coffee cup.",
            "stucks" => 1,
            "price" => 20,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 11,
            "id" => 8,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Big coffee cup",
            "image" => "bigcoffeec.jpg",
            "alt" => "Photo by Ioana Motoc from Pexels",
            "text" => "A big and nice coffee cup.",
            "stucks" => 1,
            "price" => 13,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 16,
            "id" => 9,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Big white coffee cup",
            "image" => "whitebigcoffeec.jpg",
            "alt" => "Photo by cottonbro from Pexels",
            "text" => "A big white coffee cup.",
            "stucks" => 1,
            "price" => 7,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 22,
            "id" => 10,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "White small coffee cup",
            "image" => "smallwhitecoffeec.jpg",
            "alt" => "Photo by Rachel Claire from Pexels",
            "text" => "A small white coffee cup.",
            "stucks" => 1,
            "price" => 11,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 30,
            "id" => 11,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Big pink coffee cup",
            "image" => "bigpinkcoffeec.jpg",
            "alt" => "Photo by Harper Sunday from Pexels",
            "text" => "A big pink coffee cup.",
            "stucks" => 1,
            "price" => 18,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 3,
            "id" => 12,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Green coffee cup set",
            "image" => "greencoffeec.jpg",
            "alt" => "Photo by Olga Mironova from Pexels",
            "text" => "A green coffee cup. 6 stucks.",
            "stucks" => 6,
            "price" => 64,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 38,
            "id" => 13,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "Green brown coffee cup set",
            "image" => "greenbrowncoffeec.jpg",
            "alt" => "Photo by Nida from Pexels",
            "text" => "A green brown coffee cup set. 12 stucks",
            "stucks" => 12,
            "price" => 112,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 3,
            "id" => 14,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "portable coffee cup.",
            "image" => "portablecoffeec.jpg",
            "alt" => "Photo by Quang Anh Ha Nguyen from Pexels",
            "text" => "A portable coffee cup.",
            "stucks" => 1,
            "price" => 16,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 60,
            "id" => 15,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Nice grey coffee cup.",
            "image" => "nicegreycoffeec.jpg",
            "alt" => "Photo by Anna Rye from Pexels",
            "text" => "A grey coffee cup.",
            "stucks" => 1,
            "price" => 6,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 2,
            "id" => 16,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Big beautifull coffee cup.",
            "image" => "bigbeautifullcoffeec.jpg",
            "alt" => "Photo by Karolina Grabowska from Pexels",
            "text" => "A big and beautifull coffee cup.",
            "stucks" => 1,
            "price" => 15,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 27,
            "id" => 17,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Nice orange coffee cup set.",
            "image" => "orangecoffeec.jpg",
            "alt" => "Photo by Tim Douglas from Pexels",
            "text" => "Orange and nice coffee cup set. 6 stucks",
            "stucks" => 6,
            "price" => 92,
            "onSale30" => true,
            "onSale50" => false,
            "stock" => 33,
            "id" => 18,
            "quantity" => 0,
            "category" => 'setCups',
            "show" => true,
        ],
        [
            "name" => "White and gold coffee cup.",
            "image" => "whitegoldcoffeec.jpg",
            "alt" => "Photo by Ioana Motoc from Pexels",
            "text" => "White and gold beautifull coffee cup.",
            "stucks" => 1,
            "price" => 18,
            "onSale30" => false,
            "onSale50" => true,
            "stock" => 3,
            "id" => 19,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Beautifull coffee cup.",
            "image" => "verynicecoffeec.jpg",
            "alt" => "Photo by Eneida Nieves from Pexels",
            "text" => "White and gold very nice coffee cup.",
            "stucks" => 1,
            "price" => 20,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 22,
            "id" => 20,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
        [
            "name" => "Unic coffee cup.",
            "image" => "uniccoffeec.jpg",
            "alt" => "Photo by Skyler Ewing from Pexels",
            "text" => "black and gold unic coffee cup.",
            "stucks" => 1,
            "price" => 28,
            "onSale30" => false,
            "onSale50" => false,
            "stock" => 2,
            "id" => 21,
            "quantity" => 0,
            "category" => 'perstuckCups',
            "show" => true,
        ],
    
    ];

    $sql = "TRUNCATE `cups`.`webshop`";

    query($sql);

    foreach ($cups as $cup) {
        $cup['created_at'] = date('Y-m-d H:i:s');

        insert($cup, 'cups');
    }

}