<?php

return [
    'table_name' => 'machines',

    'drop_scheme' => "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS `machines`; SET FOREIGN_KEY_CHECKS = 1",

    'scheme' => "CREATE TABLE IF NOT EXISTS `machines` (
        `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `image` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `alt` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `machineNum` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `text` TEXT,
        `price` decimal(10,2),
        `onSale30` tinyint(1) NOT NULL,
        `onSale50` tinyint(1) NOT NULL,
        `stock` int,
        `quantity` int,
        `category` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `showStatus` tinyint(1) NOT NULL,
        -- `color` varchar(120),
        `created_at` timestamp NOT NULL,
        `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
        `deleted_at` timestamp DEFAULT NULL,
        `created_by` int(11) NOT NULL,
        `updated_by` int(11),
        `deleted_by` int(11),
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;",

    'relations' => [
        'ALTER TABLE `products` ADD FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `products` ADD FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `products` ADD FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
    ],

    'seeder' => [
        'type' => 'array',
        'data' => array(
            [
                "name"          => "Simple and tasty",
                "image"         => "simplecoffem.jpg",
                "alt"           => "Photo by mentatdgt from Pexels",
                "machineNum"    => "CM357e",
                "text"          => "A simple coffee machine that makes a tasty coffee, takes no space in the kitchen.",
                "price"         => 45,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 10,
                "id"            => 1,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Profitional",
                "image"         => "profitionalcoffem.jpg",
                "alt"           => "Photo by Eka Sutrisno from Pexels",
                "machineNum"    => "CM359e",
                "text"          => "For coffee lovers, this is the one you need.",
                "price"         => 899,
                "onSale30"      => false,
                "onSale50"      => true,
                "stock"         => 4,
                "id"            => 2,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Fresh",
                "image"         => "freshcoffeem.jpg",
                "alt"           => "Photo by Matt Jerome Connor from Pexels",
                "machineNum"    => "CM356f",
                "text"          => "Always fresh coffee. With or without milk, so tasty.",
                "price"         => 150,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 8,
                "id"            => 3,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Filter",
                "image"         => "filtercoffeem.jpg",
                "alt"           => "Photo by Thirdman from Pexels",
                "machineNum"    => "CM352f",
                "text"          => "A wonderfull coffee machine. For people who love filtered coffee, this is the best.",
                "price"         => 200,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 12,
                "id"            => 4,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Easy",
                "image"         => "easycoffeem.jpg",
                "alt"           => "Photo by Ketut Subiyanto from Pexels",
                "machineNum"    => "CM363f",
                "text"          => "Nice set. Making coffee with this set is an easy and wonderfull experience.",
                "price"         => 450,
                "onSale30"      => false,
                "onSale50"      => true,
                "stock"         => 25,
                "id"            => 5,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Silver",
                "image"         => "silvercoffeem.jpg",
                "alt"           => "Photo by Karolina Grabowska from Pexels",
                "machineNum"    => "CM365f",
                "text"          => "A beautifull silver coffee machine, tasty espresso and cappuccino.",
                "price"         => 130,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 30,
                "id"            => 6,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Small & Red",
                "image"         => "smallcoffeem.jpg",
                "alt"           => "Photo by Hiago Italo from Pexels",
                "machineNum"    => "CM368e",
                "text"          => "Small but tasty. A beautifull red coffee machine that makes a tasty coffee.",
                "price"         => 99,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 0,
                "id"            => 7,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Take away and enjoy",
                "image"         => "takeawaycoffeem.jpg",
                "alt"           => "Photo by Taryn Elliott from Pexels",
                "machineNum"    => "CM369e",
                "text"          => "So tasty, so easy to use. Take it with you wherever you go.",
                "price"         => 55,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 60,
                "id"            => 8,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Handy and tasty",
                "image"         => "handycoffeem.jpg",
                "alt"           => "Photo by Maria Orlova from Pexels",
                "machineNum"    => "CM363e",
                "text"          => "Handy and easy to use coffee machine. Makes very tasty coffee.",
                "price"         => 80,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 20,
                "id"            => 9,
                "quantity"      => 0,
                "category"      => "smallmachine",
                "show"          => true,
            ],
            [
                "name"          => "Super Machine",
                "image"         => "soprofitionalcoffeem.jpg",
                "alt"           => "Photo by Ivan Samkov from Pexels",
                "machineNum"    => "CM370f",
                "text"          => "A profitional coffee machine, for coffee lovers.",
                "price"         => 999,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 8,
                "id"            => 10,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Everyday Coffee",
                "image"         => "everydaycoffeem.jpg",
                "alt"           => "Photo by Cleyder Duque from Pexels",
                "machineNum"    => "CM373e",
                "text"          => "Tasty coffee for your everyday life, for you, for your guests, for everybody.",
                "price"         => 80,
                "onSale30"      => false,
                "onSale50"      => true,
                "stock"         => 15,
                "id"            => 11,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Modern",
                "image"         => "moderncoffeem.jpg",
                "alt"           => "Photo by Jonathan Borba from Pexels",
                "machineNum"    => "CM377f",
                "text"          => "Modern coffee machine, so beautifull and tasty.",
                "price"         => 199,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 12,
                "id"            => 12,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Super easy",
                "image"         => "supereasycoffeem.jpg",
                "alt"           => "Photo by Svetlana Ponomareva from Pexels",
                "machineNum"    => "CM371e",
                "text"          => "Super easy coffee machine, for who wants tasty coffee fast.",
                "price"         => 50,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 22,
                "id"            => 13,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Arabic",
                "image"         => "arabiccoffeem.jpg",
                "alt"           => "Photo by Michaela S. from Pexels",
                "machineNum"    => "CM378e",
                "text"          => "Set for fresh bewed arabic coffee, so tasty, you'll never regret it.",
                "price"         => 80,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 10,
                "id"            => 14,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Super profitional",
                "image"         => "superprofitionalcoffeem.jpg",
                "alt"           => "Photo by Pavel Danilyuk from Pexels",
                "machineNum"    => "CM380f",
                "text"          => "Super profitional coffee machine. Tasty coffee, it's worth it.",
                "price"         => 1982,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 2,
                "id"            => 15,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Work time coffee",
                "image"         => "worktimecoffeem.jpg",
                "alt"           => "Photo by Ekrulila from Pexels",
                "machineNum"    => "CM490e",
                "text"          => "Tasty coffee. You can make it fast and start your work actively",
                "price"         => 75,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 43,
                "id"            => 16,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Time out",
                "image"         => "timeoutcoffeem.jpg",
                "alt"           => "Photo by Rachel Claire from Pexels",
                "machineNum"    => "CM495e",
                "text"          => "Drink this tasty coffee from this machine to relax and take a time out.",
                "price"         => 160,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 16,
                "id"            => 17,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Nice coffee",
                "image"         => "nicecoffeem.jpg",
                "alt"           => "Photo by Lynnelle Richardson from Pexels",
                "machineNum"    => "CM494e",
                "text"          => "Nice coffee machine that makes a tasty coffee for you.",
                "price"         => 399,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 20,
                "id"            => 18,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Coffee lovers",
                "image"         => "coffeeloverscoffeem.jpg",
                "alt"           => "Photo by Clam Lo from Pexels",
                "machineNum"    => "CM483e",
                "text"          => "If you love coffe, you will love this coffee machine.",
                "price"         => 275,
                "onSale30"      => false,
                "onSale50"      => true,
                "stock"         => 18,
                "id"            => 19,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Cappuccino lovers",
                "image"         => "cappuccinoloverscoffeem.jpg",
                "alt"           => "Photo by Pavel Danilyuk from Pexels",
                "machineNum"    => "CM400f",
                "text"          => "This coffee machine is espically for you cappuccino lovers.",
                "price"         => 2560,
                "onSale30"      => false,
                "onSale50"      => true,
                "stock"         => 9,
                "id"            => 20,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Cappuccino professional",
                "image"         => "cappuccinoprofitionalcoffeem.jpg",
                "alt"           => "Photo by Lisa from Pexels",
                "machineNum"    => "CM402f",
                "text"          => "This professional coffee machine makes a tasty cappuccino.",
                "price"         => 2470,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 11,
                "id"            => 21,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Espresso",
                "image"         => "espressocoffeem.jpg",
                "alt"           => "Photo by Sander Dalhuisen from Pexels",
                "machineNum"    => "CM410f",
                "text"          => "Tasty espresso. You'll always like it",
                "price"         => 1999,
                "onSale30"      => false,
                "onSale50"      => true,
                "stock"         => 18,
                "id"            => 22,
                "quantity"      => 0,
                "category"      => 'bigmachine',
                "show"          => true,
            ],
            [
                "name"          => "Tasty",
                "image"         => "tastycoffeem.jpg",
                "alt"           => "Photo by Ida Bagus Anggarama from Pexels",
                "machineNum"    => "CM501m",
                "text"          => "Tasty coffee. Small coffee machine that fits in small kitchens",
                "price"         => 400,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 4,
                "id"            => 23,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Small cappuccino machine",
                "image"         => "smallcappuccinocoffeem.jpg",
                "alt"           => "Photo by Noah Frohn from Pexels",
                "machineNum"    => "CM512m",
                "text"          => "This small coffee machine is perfect for a cup of cappuccino.",
                "price"         => 680,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 22,
                "id"            => 24,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Tiny",
                "image"         => "tinycoffeem.jpg",
                "alt"           => "Photo by Tim Douglas from Pexels",
                "machineNum"    => "CM514m",
                "text"          => "Tiny coffee machine. filtered coffee is the best.",
                "price"         => 89,
                "onSale30"      => true,
                "onSale50"      => false,
                "stock"         => 8,
                "id"            => 25,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
            [
                "name"          => "Unic",
                "image"         => "uniccoffeem.jpg",
                "alt"           => "Photo by Georgi Petrov from Pexels",
                "machineNum"    => "CM911m",
                "text"          => "Unic coffee machine. You will always love it.",
                "price"         => 90,
                "onSale30"      => false,
                "onSale50"      => false,
                "stock"         => 3,
                "id"            => 26,
                "quantity"      => 0,
                "category"      => 'smallmachine',
                "show"          => true,
            ],
        ),
    ]
];