<?php

return [
    'table_name' => 'cups',

    'drop_scheme' => "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS `cups`; SET FOREIGN_KEY_CHECKS = 1",

    'scheme' => "CREATE TABLE IF NOT EXISTS `cups` (
        `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `image` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `alt` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `text` TEXT,
        `info` int,
        `price` decimal(10,2),
        `onSale30` tinyint(1) NOT NULL,
        `onSale50` tinyint(1) NOT NULL,
        `stock` int,
        `quantity` int,
        `category` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `showStatus` tinyint(1) NOT NULL,
        `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
        `deleted_at` timestamp DEFAULT NULL,
        `created_by` int(11) NOT NULL,
        `updated_by` int(11),
        `deleted_by` int(11),
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;",

    'relations' => [
        'ALTER TABLE `cups` ADD FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `cups` ADD FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `cups` ADD FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
    ],

    'seeder' => [
        'type' => 'array',
        'data' => array(
            [
                "name"          => "Black coffee cup set",
                "image"         => "blackcoffeec.jpg",
                "alt"           => "Photo by Chevanon Photography from Pexels",
                "text"          => "A beautifull set of coffee cups. 6 stuks",
                "info"        => 6,
                "price"         => 35,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 120,
                "id"            => 1,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Beautifull brown coffee cup",
                "image"         => "nicebrowncoffeec.jpg",
                "alt"           => "Photo by Pelageia Zelenina from Pexels",
                "text"          => "A beautifull coffee cup.",
                "info"        => 1,
                "price"         => 15,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 2,
                "id"            => 2,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "brown coffee cup set",
                "image"         => "browncoffeec.jpg",
                "alt"           => "Photo by Valeriia Miller from Pexels",
                "text"          => "A beautifull set of coffee cups. 2 stuks",
                "info"        => 6,
                "price"         => 15,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 80,
                "id"            => 3,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "White coffee cup Set",
                "image"         => "whitecoffeec.jpg",
                "alt"           => "Photo by Alin Luna from Pexels",
                "text"          => "A nice white set of coffee cups. 6 stuks",
                "info"        => 6,
                "price"         => 40,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 10,
                "id"            => 4,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Grey coffee cup Set",
                "image"         => "greycoffeec.jpg",
                "alt"           => "Photo by Vitaly Vlasov from Pexels",
                "text"          => "A large grey set of coffee cups. 6 stuks",
                "info"        => 6,
                "price"         => 58,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 5,
                "id"            => 5,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Nice coffee cup Set",
                "image"         => "nicecoffeec.jpg",
                "alt"           => "Photo by Marta Dzedyshko from Pexels",
                "text"          => "A nice beautifull set of coffee cups. 12 stuks",
                "info"        => 12,
                "price"         => 120,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 15,
                "id"            => 6,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Pottery coffee cup",
                "image"         => "potterycoffeec.jpg",
                "alt"           => "Photo by Cup of Couple from Pexels",
                "text"          => "A pottery beautifull coffee cup.",
                "info"        => 1,
                "price"         => 12,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 20,
                "id"            => 7,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Beautifull coffee cup",
                "image"         => "beautifullcoffeec.jpg",
                "alt"           => "Photo by SpotwizardLee from Pexels",
                "text"          => "A beautifull and cozy coffee cup.",
                "info"        => 1,
                "price"         => 20,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 11,
                "id"            => 8,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Big coffee cup",
                "image"         => "bigcoffeec.jpg",
                "alt"           => "Photo by Ioana Motoc from Pexels",
                "text"          => "A big and nice coffee cup.",
                "info"        => 1,
                "price"         => 13,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 16,
                "id"            => 9,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Big white coffee cup",
                "image"         => "whitebigcoffeec.jpg",
                "alt"           => "Photo by cottonbro from Pexels",
                "text"          => "A big white coffee cup.",
                "info"        => 1,
                "price"         => 7,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 22,
                "id"            => 10,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "White small coffee cup",
                "image"         => "smallwhitecoffeec.jpg",
                "alt"           => "Photo by Rachel Claire from Pexels",
                "text"          => "A small white coffee cup.",
                "info"        => 1,
                "price"         => 11,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 30,
                "id"            => 11,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Big pink coffee cup",
                "image"         => "bigpinkcoffeec.jpg",
                "alt"           => "Photo by Harper Sunday from Pexels",
                "text"          => "A big pink coffee cup.",
                "info"        => 1,
                "price"         => 18,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 3,
                "id"            => 12,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Green coffee cup set",
                "image"         => "greencoffeec.jpg",
                "alt"           => "Photo by Olga Mironova from Pexels",
                "text"          => "A green coffee cup. 6 info.",
                "info"        => 6,
                "price"         => 64,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 38,
                "id"            => 13,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Green brown coffee cup set",
                "image"         => "greenbrowncoffeec.jpg",
                "alt"           => "Photo by Nida from Pexels",
                "text"          => "A green brown coffee cup set. 12 info",
                "info"        => 12,
                "price"         => 112,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 3,
                "id"            => 14,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "portable coffee cup.",
                "image"         => "portablecoffeec.jpg",
                "alt"           => "Photo by Quang Anh Ha Nguyen from Pexels",
                "text"          => "A portable coffee cup.",
                "info"        => 1,
                "price"         => 16,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 60,
                "id"            => 15,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Nice grey coffee cup.",
                "image"         => "nicegreycoffeec.jpg",
                "alt"           => "Photo by Anna Rye from Pexels",
                "text"          => "A grey coffee cup.",
                "info"        => 1,
                "price"         => 6,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 2,
                "id"            => 16,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Big beautifull coffee cup.",
                "image"         => "bigbeautifullcoffeec.jpg",
                "alt"           => "Photo by Karolina Grabowska from Pexels",
                "text"          => "A big and beautifull coffee cup.",
                "info"        => 1,
                "price"         => 15,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 27,
                "id"            => 17,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Nice orange coffee cup set.",
                "image"         => "orangecoffeec.jpg",
                "alt"           => "Photo by Tim Douglas from Pexels",
                "text"          => "Orange and nice coffee cup set. 6 info",
                "info"        => 6,
                "price"         => 92,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 33,
                "id"            => 18,
                "quantity"      => 0,
                "category"      => 'setCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "White and gold coffee cup.",
                "image"         => "whitegoldcoffeec.jpg",
                "alt"           => "Photo by Ioana Motoc from Pexels",
                "text"          => "White and gold beautifull coffee cup.",
                "info"        => 1,
                "price"         => 18,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 3,
                "id"            => 19,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Beautifull coffee cup.",
                "image"         => "verynicecoffeec.jpg",
                "alt"           => "Photo by Eneida Nieves from Pexels",
                "text"          => "White and gold very nice coffee cup.",
                "info"        => 1,
                "price"         => 20,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 22,
                "id"            => 20,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "Unic coffee cup.",
                "image"         => "uniccoffeec.jpg",
                "alt"           => "Photo by Skyler Ewing from Pexels",
                "text"          => "black and gold unic coffee cup.",
                "info"        => 1,
                "price"         => 28,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 2,
                "id"            => 21,
                "quantity"      => 0,
                "category"      => 'perstuckCups',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
        ),
    ]
];