
<?php

return [
    'table_name' => 'beans',

    'drop_scheme' => "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS `beans`; SET FOREIGN_KEY_CHECKS = 1",

    'scheme' => "CREATE TABLE IF NOT EXISTS `beans` (
        `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `image` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `alt` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `text` TEXT,
        `info` float(10,2),
        `price` decimal(10,2),
        `onSale30` tinyint(1) NOT NULL,
        `onSale50` tinyint(1) NOT NULL,
        `stock` int,
        `quantity` int,
        `category` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `showStatus` tinyint(1) NOT NULL,
        `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
        `deleted_at` timestamp DEFAULT NULL,
        `created_by` int(11) NOT NULL,
        `updated_by` int(11),
        `deleted_by` int(11),
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;",

    'relations' => [
        'ALTER TABLE `beans` ADD FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `beans` ADD FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `beans` ADD FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
    ],

    'seeder' => [
        'type' => 'array',
        'data' => array(
            [
                "name"          => "INDONESIA Medium",
                "image"         => "beans1.jpg",
                "alt"           => "Photo by Cup of Couple from Pexels",
                "text"          => "Indonesian coffee beans. Tasty coffee espically for cappuccino.",
                "info"        => 1,
                "price"         => 25,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 30,
                "id"            => 1,
                "quantity"      => 0,
                "category"      => 'medium',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "COLOMBIA Medium",
                "image"         => "beans2.jpg",
                "alt"           => "Photo by Cup of Couple from Pexels",
                "text"          => "colombian coffee beans.",
                "info"        => 1,
                "price"         => 28,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 50,
                "id"            => 2,
                "quantity"      => 0,
                "category"      => 'medium',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "COLOMBIA Blond",
                "image"         => "beans3.jpg",
                "alt"           => "Photo by Denys Gromov from Pexels",
                "text"          => "Colombian coffee beans.",
                "info"        => 0.5,
                "price"         => 13,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 2,
                "id"            => 3,
                "quantity"      => 0,
                "category"      => 'blond',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "BRAZIL Dark",
                "image"         => "beans4.jpg",
                "alt"           => "Photo by Thirdman from Pexels",
                "text"          => "Brazilian coffee beans.",
                "info"        => 1,
                "price"         => 30,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 34,
                "id"            => 4,
                "quantity"      => 0,
                "category"      => 'dark',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "BRAZIL Blond",
                "image"         => "beans5.jpg",
                "alt"           => "Photo by Los Muertos Crew from Pexels",
                "text"          => "Brazilian coffee beans.",
                "info"        => 1,
                "price"         => 28,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 9,
                "id"            => 5,
                "quantity"      => 0,
                "category"      => 'blond',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "INDIA Dark",
                "image"         => "beans6.jpg",
                "alt"           => "istock",
                "text"          => "Indian coffee beans.",
                "info"        => 1,
                "price"         => 30,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 3,
                "id"            => 6,
                "quantity"      => 0,
                "category"      => 'dark',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "ETHIOPIA Medium",
                "image"         => "beans7.jpg",
                "alt"           => "Photo by Ave Calvar Martinez from Pexels",
                "text"          => "Ethiopian coffee beans.",
                "info"        => 1,
                "price"         => 27,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 9,
                "id"            => 7,
                "quantity"      => 0,
                "category"      => 'medium',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "INDIA Medium",
                "image"         => "beans8.jpg",
                "alt"           => "Photo by bacho nadiradze from Pexels",
                "text"          => "Indian coffee beans.",
                "info"        => 0.5,
                "price"         => 12,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 2,
                "id"            => 8,
                "quantity"      => 0,
                "category"      => 'medium',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "ETHIOPIA Blond",
                "image"         => "beans9.jpg",
                "alt"           => "Photo by Cup of Couple from Pexels ",
                "text"          => "Ethiopian coffee beans.",
                "info"        => 1,
                "price"         => 29,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 17,
                "id"            => 9,
                "quantity"      => 0,
                "category"      => 'blond',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "INDIA Blond",
                "image"         => "beans10.jpg",
                "alt"           => "Photo by Alexas Fotos from Pexels ",
                "text"          => "Inidan coffee beans.",
                "info"        => 1,
                "price"         => 30,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 22,
                "id"            => 10,
                "quantity"      => 0,
                "category"      => 'blond',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "INDONESIA Blond",
                "image"         => "beans11.jpg",
                "alt"           => "Photo by Engin Akyurt from Pexels",
                "text"          => "Indonesian coffee beans.",
                "info"        => 1,
                "price"         => 27,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 4,
                "id"            => 11,
                "quantity"      => 0,
                "category"      => 'blond',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "INDONESIA Dark",
                "image"         => "beans12.jpg",
                "alt"           => "Photo by Ryutaro Tsukata from Pexels",
                "text"          => "Indonesian coffee beans.",
                "info"        => 1,
                "price"         => 30,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 44,
                "id"            => 12,
                "quantity"      => 0,
                "category"      => 'dark',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "BRAZIL Medium",
                "image"         => "beans13.jpg",
                "alt"           => "Photo by Cup of Couple from Pexels",
                "text"          => "Barazilian coffee beans.",
                "info"        => 0.5,
                "price"         => 14,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 83,
                "id"            => 13,
                "quantity"      => 0,
                "category"      => 'medium',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "VIETNAM Blond",
                "image"         => "beans14.jpg",
                "alt"           => "Photo by cottonbro from Pexels",
                "text"          => "Veitnamian coffee beans.",
                "info"        => 1,
                "price"         => 25,
                "onSale30"      => 1,
                "onSale50"      => 0,
                "stock"         => 60,
                "id"            => 14,
                "quantity"      => 0,
                "category"      => 'blond',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "VIETNAM Dark",
                "image"         => "beans15.jpg",
                "alt"           => "Photo by Nicola Barts from Pexels",
                "text"          => "Veitnamian coffee beans.",
                "info"        => 1,
                "price"         => 28,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 4,
                "id"            => 15,
                "quantity"      => 0,
                "category"      => 'dark',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "VIETNAM Medium",
                "image"         => "beans16.jpg",
                "alt"           => "Photo by lyncoln Miller from Pexels",
                "text"          => "Veitnamian coffee beans.",
                "info"        => 1,
                "price"         => 27,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 58,
                "id"            => 16,
                "quantity"      => 0,
                "category"      => 'medium',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "PERU Blond",
                "image"         => "beans17.jpg",
                "alt"           => "Photo by Mariakray from Pexels",
                "text"          => "Peruvian coffee beans.",
                "info"        => 1,
                "price"         => 28,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 45,
                "id"            => 17,
                "quantity"      => 0,
                "category"      => 'blond',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "PERU Dark",
                "image"         => "beans18.jpg",
                "alt"           => "Photo by Pavel Danilyuk from Pexels",
                "text"          => "Peruvian coffee beans.",
                "info"        => 0.5,
                "price"         => 16,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 56,
                "id"            => 18,
                "quantity"      => 0,
                "category"      => 'dark',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "UGANDA Medium",
                "image"         => "beans19.jpg",
                "alt"           => "Photo by Cup of Couple from Pexels",
                "text"          => "Ugandan coffee beans.",
                "info"        => 1,
                "price"         => 26,
                "onSale30"      => 0,
                "onSale50"      => 1,
                "stock"         => 54,
                "id"            => 19,
                "quantity"      => 0,
                "category"      => 'medium',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
            [
                "name"          => "UGANDA Dark",
                "image"         => "beans20.jpg",
                "alt"           => "Photo by Lisa from Pexels",
                "text"          => "Ugandan coffee beans.",
                "info"        => 1,
                "price"         => 28,
                "onSale30"      => 0,
                "onSale50"      => 0,
                "stock"         => 30,
                "id"            => 20,
                "quantity"      => 0,
                "category"      => 'dark',
                "showStatus"    => true,
                'created_at'    => date('Y-m-d H:i:s'),
                'created_by'    => 2,
            ],
        
        ),
    ]
];